baseURL = "https://salvaivars.github.io/"
locale = "en"
title = "✰Salva✰"
author = "Salva"
copyright = "© Salva"
theme = "hugo-bearblog"
enableRobotsTXT = true

[params]
  description = "Salva's personal website: programming, artificial intelligence and projects."
  dateFormat = "2006-01-02"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 4

[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/salva-ivars/"
  weight = 5

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/SalvaIvars"
  weight = 6

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
